### ISSUE TITLE
it's possible to support on the bridge session,and send a or b leg different audio stream ?

### ISSUE THREAD

**Issue by herbiel** [amigniter/mod_audio_stream#23]
it's possible to support on the bridge session,and send a or b leg different audio stream ?

**Comment by amigniter** [comment]
Yes, it is possible to stream either the A-leg or B-leg from a bridged call using the provided API method from the module. There is no need for any additional support from the module itself. The module offers an API method to stream audio from a channel, and it is entirely up to the user to implement this method. With access to this API method, users can achieve any functionality possible within FS. However, it's important to note that a certain level of knowledge and experience with FS is still required to effectively utilize these capabilities.

While I'm here to provide support and guidance to the best of my ability, it's important to note that due to time constraints and the diversity of use cases, I may not be able to offer assistance or work out every specific scenario.
However, I'm committed to helping as many users as possible and providing general guidance and troubleshooting tips. I believe there will be users trying to achieve the same, so here is one approach how to accomplish this scenario.

```
<action application="set" data="api_on_answer=luarun stream_audio.lua ${uuid}"/>
<action application="bridge" data="sofia/gateway/virtualbox/1019"/>
```

This is a segment from dialplan. I am using `api_on_answer` here which will be executed on the bridge successfully established. You can 't call the api method directly here but need to provide a script which will handle the api, so i am using lua here. What's important to note, since it is an api call, session object is not available and we need to pass uuid to the script. You can't retrieve the session variables etc., as session is not accessible. 

```lua
local api = freeswitch.API()
local session_uuid = argv[1]

if session_uuid then
    freeswitch.consoleLog("info", session_uuid .. "\n")

    local dump_output = api:execute("uuid_dump", session_uuid)
    freeswitch.consoleLog("info", dump_output)

    local channel_call_uuid = dump_output:match("Channel%-Call%-UUID:%s*(%S+)")

    if channel_call_uuid then
        freeswitch.consoleLog("info", "Channel-Call-UUID: " .. channel_call_uuid .. "\n")
        api:execute("uuid_audio_stream", channel_call_uuid .. " start ws://192.168.0.19:5000 mono 8k")
    else
        freeswitch.consoleLog("err", "Channel-Call-UUID not found in dump output\n")
    end
end
```
This is `stream_audio.lua` script. As you can see I am dumping out variables from the session to get the _Channel-Call-UUID_, which is the A-leg in this case. If I am right, the other bridged leg is _Other-Leg-UUID_. I am printing to the console the entire dump output so you can search for the variables. 

I hope I helped with this example. Best regards!

**Comment by herbiel** [comment]
thanks you for your help ,best wish

**Comment by herbiel** [comment]
i install freeswitch with apt install,i can't find the pkg ,how to do it ?
