### ISSUE TITLE
Incorrect sampling rate

### ISSUE THREAD

**Issue by sjoerdsmink** [amigniter/mod_audio_stream#25]
It seems the audio output sent to the websocket is corrupt. I'm running `uuid_audio_stream <uuid> start ws://localhost:3000 mixed 16k abc` with this JavaScript file:
```
const WebSocket = require('ws');
const fs = require('fs');

const recordingPath = '/tmp/audio.raw';
const port = 3000;
let wstream;

console.log(`listening on port ${port}, writing incoming raw audio to file ${recordingPath}`);

const wss = new WebSocket.Server({port});

wss.on('connection', (ws, req) => {
  console.log(`received connection from ${req.connection.remoteAddress}`);
  wstream = fs.createWriteStream(recordingPath);

  ws.on('message', (message, binary) => {
    if (!binary) {
      console.log(`received message: ${message}`);
    } else {
      wstream.write(message);
    }
  });

  ws.on('close', (code, reason) => {
    console.log(`socket closed ${code}:${reason}`);
    wstream.end();
  });
});
```

In case you're unfamiliar with Node, you can run it using
```
apt-get install nodejs npm
npm install -g ws
node <filename>.js
```

I'm getting [this audio.raw file](https://github.com/user-attachments/files/15621070/audio.raw.zip) in `/tmp/audio.raw` which even Audacity can't do anything with. I'm running Debian 12 and installed FreeSwitch using the [compiling release branch documentation](https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Installation/Linux/Debian_67240088#compiling-release-branch-production).

Any suggestions?

**Comment by sjoerdsmink** [comment]
It seems that when using `mono` or `mixed` it's 8kHz, but when using `stereo` it's 16kHz. I assumed sampling rate would be applied to all options, but this is not the case? Or is this a bug?

**Comment by amigniter** [comment]
You used `uuid_audio_stream <uuid> start ws://localhost:3000 mixed 16k abc` and the produced _audio.raw_ comes from this session, right? Then this raw audio file looks correct to me, 16bit-16000kHz-mono and API generated exactly what you told it to do. `Mixed` means to mix both the caller and the callee to a single (mono) channel. It is resampled to 16khz, so no, it is not a bug. You could have used `mono 16k abc` (since you are streaming from a single, not bridged, channel) and the audio will be the same, mono, and at 16khz.
```bash 
aplay -r 16000 -c 1 -f S16_LE audio.raw
```
This is how you can play your audio, `-c` number of channels and `-r` sample rate.

**Comment by sjoerdsmink** [comment]
Thanks for looking into it. Using `uuid_audio_stream <uuid> start ws://localhost:3000 mixed 16k abc` I created three files:
1. [mono.raw.zip](https://github.com/user-attachments/files/15722180/mono.raw.zip)
2. [mixed.raw.zip](https://github.com/user-attachments/files/15722184/mixed.raw.zip)
3. [stereo.raw.zip](https://github.com/user-attachments/files/15722187/stereo.raw.zip)

I don't have aplay, but checked using importing raw data in Audacity. It seems to me that mono and mixed have to played at 8kHz, while stereo at 16kHz.

Could you recheck with these files? Also with aplay check how it will be played on 8kHz; you should be able to hear my voice saying "testing <type>" clearly.

**Comment by amigniter** [comment]
> It seems to me that mono and mixed have to played at 8kHz, while stereo at 16kHz.
I see what you mean. You actually expect mono or mixed to be at 8khz. That's not the case here. API is called with `mono 16k` and what you told it by this is: `put the audio into the single channel (caller only) and resample it to 16khz`. Default FS sample rate is 8khz and it is properly resampled to 16khz, as expected. If you want mono or mixed at 8khz you need to call the API with `mono|mixed 8k`.

> Could you recheck with these files? Also with aplay check how it will be played on 8kHz; you should be able to hear my voice saying "testing " clearly.
All of these files look correct. If the command was the same and you only changed mono,mixed or stereo but 16k in each command, produced audio files are correct. They are all at 16khz (as expected by the issued command), mono and mixed have one channel and stereo has two.
So, we tell the API the sample rate our streamed audio is going to be at. If you used `mono 16k` you can't expect it to be at 8k since you told it already that you want it at 16k. Hope that we've shed some more light on this.

**Comment by sjoerdsmink** [comment]
I did actually expected them all to be 16kHz, but mono and mixed seemed to be at 8kHz. However, I checked again using ffmpeg and exporting it as wav. This time all files were indeed 16k. I think the confusion was because when importing it in Audacity, I had stereo selected for mono and mixed, which resulted in incorrect rendering. Thanks for checking.
