### ISSUE TITLE
STREAM_BUFFER_SIZE blocks sending data

### ISSUE THREAD

**Issue by sjoerdsmink** [amigniter/mod_audio_stream#27]
When setting `STREAM_BUFFER_SIZE` it seems the websocket connection is created and closed properly, but no data is sent. 

I'm using this JavaScript file:
```
const WebSocket = require('ws');

const port = 3000;
console.log(`listening on port ${port}`);
const wss = new WebSocket.Server({port});

wss.on('connection', (ws, req) => {
  console.log(`received connection from ${req.connection.remoteAddress}`);

  ws.on('message', (message, binary) => {
    if (!binary) {
      console.log(`${new Date().toISOString()} received message: ${message}`);
    } else {
      console.log(`${new Date().toISOString()} data`);
    }
  });

  ws.on('close', (code, reason) => {
    console.log(`${new Date().toISOString()} socket closed ${code}:${reason}`);
  });
});
```

When I'm executing `uuid_audio_stream <uuid> start ws://localhost:3000 stereo 16k abc` in `fs_cli` the output is:
```
listening on port 3000
received connection from ::1
2024-06-07T08:53:35.421Z received message: abc
2024-06-07T08:53:35.424Z data
2024-06-07T08:53:35.434Z data
2024-06-07T08:53:35.457Z data
[...]
2024-06-07T08:53:39.020Z socket closed 1000:Normal closure
```

But for the second call I'm setting `STREAM_BUFFER_SIZE` in `fs_cli` using `uuid_setvar <uuid> STREAM_BUFFER_SIZE 100` and with `uuid_getvar <uuid> STREAM_BUFFER_SIZE` I can check this is indeed set for this channel. When running `uuid_audio_stream <uuid> start ws://localhost:3000 stereo 16k abc` the output is:
```
listening on port 3000
received connection from ::1
2024-06-07T08:54:32.407Z received message: abc
2024-06-07T08:54:37.234Z socket closed 1000:Normal closure
```

So it seems there is no data received.

**Comment by amigniter** [comment]
Normally it shouldn't happen. Buffer size is extremely important. When you don't set it (default 20ms buffer is used then) it is sent correctly, but if you use 100ms chunk size there is no data ( I see the connection is closed immediately after receiving text 'abc'). I will investigate this and let you know as soon as I check it.

**Comment by amigniter** [comment]
Yes, there was an issue when the buffer is used (other than default of 20ms) and resampler, when you resample e.g. from 8k to 16k. Good find! This issue is fixed now. It was a specific edge case (since the buffer is in pow2 size) and after filling up the remaining space is 1 byte only. Now sample aligned buffer is used when resampling is required and there will be no such edge cases. I think it is all good now and the streamer is bugs free.

One thing to note. To resample the audio to 16k for example, using `stereo` or `mixed` mode, you need to have both a-leg and b-leg (channel has to be bridged). FS will look for the bridged channel and if not found the media bug won't enter the reading state. You will have the connection opened (at the ws end) but no data coming as nothing is streamed actually. To use stereo or mixed mode, both the caller and the callee are required. Single channels are streamed with mono and resampled if needed.

**Comment by sjoerdsmink** [comment]
It seems to be working now, thanks for fixing it quickly.
