### ISSUE TITLE
Writing incoming audio to a file

### ISSUE THREAD

**Issue by eadz** [amigniter/mod_audio_stream#31]
Hi,

Excuse my ignorance, but why is incoming audio written to a file?

https://github.com/amigniter/mod_audio_stream/blob/main/audio_streamer_glue.cpp#L203

Does freeswitch not have a way for you to send the audio directly?

**Comment by amigniter** [comment]
The idea is just to get the response (and not to play the file, of course it can be played) and it's user's responsibility to play the file. Received b64 audio can be played to a channel, other channel (if session is bridged), or both. If module was to play the file it can't know where the user wants to play it to. This way the user has the control and that's why it is left to the user.

**Comment by amigniter** [comment]
You're welcome @eadz 
> Is modification of this module required to do that?
Yes it is.  Currently the module is saving the file and sending an event so user can respond to it.

**Comment by amigniter** [comment]
@eadz Is there a specific reason why you'd want to play the audio to the channel directly from a module? You'd have greater control from the ESL connection while listening to the events, and you can choose the channel (caller, callee or both). That's why it is up to the user to choose.
